### PR TITLE
Fix issue #1111 by not creating MethodType on each invocation

### LINKED ISSUE #1111: WrongMethodTypeException after upgrade to 3.1.7
I don't have a reproducer for this yet, but I've seen it pop up in a variety of contexts when building a caffeine cache. This has occurred on a few configurations using both `build` and `buildAsync`. #905 seems like the most likely culprit.

```
java.lang.invoke.WrongMethodTypeException: expected ()NodeFactory but found ()NodeFactory
	at java.base/java.lang.invoke.Invokers.newWrongMethodTypeException(Invokers.java:523)
	at java.base/java.lang.invoke.Invokers.checkExactType(Invokers.java:532)
	at com.github.benmanes.caffeine.cache.NodeFactory.newFactory(NodeFactory.java:152)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at com.github.benmanes.caffeine.cache.NodeFactory.loadFactory(NodeFactory.java:141)
	at com.github.benmanes.caffeine.cache.NodeFactory.newFactory(NodeFactory.java:89)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.<init>(BoundedLocalCache.java:269)
	at com.github.benmanes.caffeine.cache.SS.<init>(Unknown Source)
	at com.github.benmanes.caffeine.cache.SSL.<init>(Unknown Source)
	at com.github.benmanes.caffeine.cache.SSLMW.<init>(Unknown Source)
	at com.github.benmanes.caffeine.cache.SSLMWA.<init>(Unknown Source)
	at com.github.benmanes.caffeine.cache.LocalCacheFactory.newBoundedLocalCache(LocalCacheFactory.java:47)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:3952)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:3948)
	at com.github.benmanes.caffeine.cache.Caffeine.build(Caffeine.java:1048)
```

### PR DESCRIPTION
**Pull request by uschindler**
This is to work around a possible concurrency bug in JDK.

This closes #1111

### CODE REVIEW

**Review by ben-manes — APPROVED** [review]

File: caffeine/src/main/java/com/github/benmanes/caffeine/cache/LocalCacheFactory.java [hunk 1]
```diff
@@ -118,10 +119,9 @@ final class MethodHandleBasedFactory implements LocalCacheFactory {
     final MethodHandle methodHandle;
 
     MethodHandleBasedFactory(Class<?> clazz) throws NoSuchMethodException, IllegalAccessException {
-      var constructor = LOOKUP.findConstructor(clazz, FACTORY);
-      this.methodHandle = constructor.asType(
-          constructor.type().changeReturnType(BoundedLocalCache.class));
+      this.methodHandle = LOOKUP.findConstructor(clazz, FACTORY).asType(FACTORY_CALL);
```
Comment (uschindler) [inline caffeine/src/main/java/com/github/benmanes/caffeine/cache/LocalCacheFactory.java:122]: To actually test that thins works, I ran a few tests here with the above VarHandle lookup for the `FACTORY` field commented out. By that I ensured this `MethodHandleBasedFactory` is always used.

Do we have Emma or similar to verify that all code is tested?

Comment (ben-manes) [reply caffeine/src/main/java/com/github/benmanes/caffeine/cache/LocalCacheFactory.java:122]: Yes, once the CI passes then the jacoco coverage will be uploaded to [coveralls](https://coveralls.io/github/ben-manes/caffeine). That shows statement coverage.

I also setup [codecov](https://app.codecov.io/gh/ben-manes/caffeine) and [sonarqube](https://sonarcloud.io/project/overview?id=com.github.ben-manes.caffeine%3Acaffeine) which show branch coverage.

Comment (uschindler) [reply caffeine/src/main/java/com/github/benmanes/caffeine/cache/LocalCacheFactory.java:122]: It looks like it executes both variants (using `FACTORY` field and the dynamic one). I was just unsure, which one is used, because the fallback looks like not used under normal circumstances: https://coveralls.io/builds/61811130/source?filename=caffeine%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fbenmanes%2Fcaffeine%2Fcache%2FLocalCacheFactory.java

Comment (ben-manes) [reply caffeine/src/main/java/com/github/benmanes/caffeine/cache/LocalCacheFactory.java:122]: Looks like full coverage!

Comment (ben-manes) [reply caffeine/src/main/java/com/github/benmanes/caffeine/cache/LocalCacheFactory.java:122]: Oh yes, I wrote a test to force the fallback just to be safe

Comment (ben-manes) [reply caffeine/src/main/java/com/github/benmanes/caffeine/cache/LocalCacheFactory.java:122]: I think it was this one or else related tests

https://github.com/ben-manes/caffeine/blob/master/caffeine/src/test/java/com/github/benmanes/caffeine/cache/BoundedLocalCacheTest.java#L2574
